# Coin Flips and Die Rolls
Use NumPy to create simulations and compute proportions for the following outcomes. The first one is done for you.

In [1]:
# import numpy
import numpy as np

### 1. Two fair coin flips produce exactly two heads

In [33]:
# simulate 1 million tests of two fair coin flips
# 0 represents heads and 1 tails
tests = np.random.randint(2, size=(int(1e6), 2)) # size=(rows, cols)

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

0.250612

In [34]:
len(tests)

1000000

In [39]:
tests[:5]

array([[0, 0],
       [1, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [31]:
len(test_sums)

1000000

In [40]:
test_sums[:5] 
# so the 2 at index 3 means 2 tails; 
# the 0 at index 0 means 2 heads

array([0, 1, 1, 2, 1])

### 2. Three fair coin flips produce exactly one head

In [49]:
# simulate 1 million tests of three fair coin flips
tests = np.random.randint(2, size=(int(1e6), 3))  # size=(rows, cols)

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()

0.37501200000000001

In [46]:
tests[:5]

array([[0, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 1],
       [0, 1, 1]])

In [47]:
test_sums[:10]

array([0, 1, 1, 2, 2, 1, 3, 2, 1, 1])

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [51]:
# simulate 1 million tests of three bias coin flips
# hint: use np.random.choice()
tests = np.random.choice([0, 1], size=(int(1e6), 3), p=[0.6, 0.4])

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()

0.28775200000000001

In [52]:
tests[:5]

array([[0, 1, 0],
       [1, 1, 0],
       [1, 0, 1],
       [0, 0, 1],
       [1, 1, 0]])

In [53]:
test_sums[:5]

array([1, 2, 2, 1, 2])

### 4. A die rolls an even number

In [54]:
# simulate 1 million tests of one die roll
tests = np.random.choice(np.arange(1, 7), size=int(1e6))

# proportion of tests that produced an even number
(tests % 2 == 0).mean()

0.500753

In [59]:
np.arange(1, 7)

array([1, 2, 3, 4, 5, 6])

In [55]:
tests[:5]

array([4, 3, 6, 2, 2])

### 5. Two dice roll a double

In [56]:
# simulate the first million die rolls
first = np.random.choice(np.arange(1, 7), size=int(1e6))

# simulate the second million die rolls
second = np.random.choice(np.arange(1, 7), size=int(1e6))

# proportion of tests where the 1st and 2nd die rolled the same number
(first == second).mean()

0.16711699999999999