# Simulating Coin Flips

In [1]:
import numpy as np
import matplotlib.pyplot as plt
% matplotlib inline

In [13]:
# outcome of one coin flip
np.random.randint(2)

1

In [14]:
# outcomes of ten thousand coin flips
np.random.randint(2, size=10000)

array([1, 0, 1, ..., 1, 0, 1])

In [20]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.49490000000000001

In [25]:
# outcome of one coin flip
np.random.choice([0, 1])

0

In [26]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([1, 1, 0, ..., 1, 1, 1])

In [27]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.49099999999999999

In [28]:
# outcomes of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])

array([0, 0, 0, ..., 0, 0, 0])

In [29]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.1933